"""Build src/data/exercises.ts from free-exercise-db (Unlicense / public domain).

Usage: python3 scripts/build-exercises.py
Downloads the dataset, keeps equipment == "kettlebells", tidies the names,
assigns a movement pattern and adds a few staples written for Kettlebelt.
"""
import json
import os
import re
import urllib.request

SRC = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json'
IMG = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/'
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'exercises.ts')

RULES = [
    ('getup', r'Get-Up'),
    ('squat', r'Squat|Lunge|Thruster|Pistol'),
    ('hinge', r'Snatch|Swing|Clean|Deadlift|High Pull|Pass Between|Figure 8'),
    ('push', r'Press|Jerk|Pushup|Triceps'),
    ('pull', r'Row'),
    ('core', r'Windmill|Halo|Pirate|Seesaw'),
]


def pattern(name):
    for key, rx in RULES:
        if re.search(rx, name, re.I):
            return key
    return 'core'


def tidy(name):
    n = re.sub(r'\s+', ' ', name.replace('Kettlebells', '').replace('Kettlebell', '')).strip()
    n = n.replace('Front Squats With Two', 'Front squat, two bells')
    n = n.replace('Swings', 'Swing').replace('Squats', 'Squat').replace('Pushups', 'Push-ups')
    n = n.replace('Two-Arm', 'Two-hand').replace('One-Arm', 'One-arm')
    n = n[0].upper() + n[1:].lower()
    return n.replace('turkish', 'Turkish')


EXTRA = [
    {'id': 'kb-two-hand-swing', 'name': 'Two-hand swing', 'pattern': 'hinge', 'level': 'beginner',
     'primary': ['hamstrings'], 'secondary': ['glutes', 'lower back', 'forearms'],
     'instructions': ['Stand with feet a little wider than hips, bell about a foot in front of you.',
                      'Hinge at the hips with a flat back and grab the handle with both hands.',
                      'Hike the bell back between your legs like a football snap.',
                      'Stand up explosively by driving the hips forward; let the bell float to chest height.',
                      'Let the bell fall back and hinge again, keeping the arms relaxed.']},
    {'id': 'kb-deadlift', 'name': 'Deadlift', 'pattern': 'hinge', 'level': 'beginner',
     'primary': ['hamstrings'], 'secondary': ['glutes', 'lower back', 'quadriceps'],
     'instructions': ['Stand with the bell between your feet, handle in line with your ankles.',
                      'Push the hips back, keep your back flat and grip the handle with both hands.',
                      'Brace and stand up tall by pushing the floor away.',
                      'Lower the bell under control by hinging back the same way.']},
    {'id': 'kb-farmer-carry', 'name': 'Farmer carry', 'pattern': 'carry', 'level': 'beginner',
     'primary': ['forearms'], 'secondary': ['traps', 'abdominals', 'shoulders'],
     'instructions': ['Deadlift a bell in each hand.', 'Stand tall with shoulders down and back.',
                      'Walk with short, steady steps for the set distance or time.',
                      'Set the bells down by hinging, not rounding your back.']},
    {'id': 'kb-suitcase-carry', 'name': 'Suitcase carry', 'pattern': 'carry', 'level': 'beginner',
     'primary': ['abdominals'], 'secondary': ['forearms', 'traps'],
     'instructions': ['Deadlift one bell to your side.', 'Stand tall without leaning toward or away from the bell.',
                      'Walk with steady steps, keeping hips and shoulders level.', 'Switch hands and repeat.']},
    {'id': 'kb-biceps-curl', 'name': 'Biceps curl', 'pattern': 'pull', 'level': 'beginner', 'mechanic': 'isolation',
     'primary': ['biceps'], 'secondary': ['forearms'],
     'instructions': ['Hold a bell by the handle, arm straight at your side, palm facing forward.',
                      'Keep the elbow pinned to your ribs and curl the bell up to the shoulder.',
                      'Squeeze at the top, then lower slowly until the arm is straight.',
                      'Do all reps on one side, then switch.']},
    {'id': 'kb-hammer-curl', 'name': 'Hammer curl', 'pattern': 'pull', 'level': 'beginner', 'mechanic': 'isolation',
     'primary': ['biceps'], 'secondary': ['forearms'],
     'instructions': ['Hold a bell by the horns or handle with your palm facing your body.',
                      'Keep the elbow still and curl the bell up toward the shoulder.',
                      'Lower under control without swinging the body.']},
    {'id': 'kb-rack-carry', 'name': 'Rack carry', 'pattern': 'carry', 'level': 'intermediate',
     'primary': ['abdominals'], 'secondary': ['shoulders', 'forearms'],
     'instructions': ['Clean a bell to the rack position: wrist straight, bell on the forearm, elbow tucked.',
                      'Brace your midsection and stand tall.', 'Walk with steady steps for the set distance.',
                      'Switch sides and repeat.']},
]

HEADER = '''/**
 * Kettlebell exercise library. GENERATED by scripts/build-exercises.py; edit the script, not this file.
 *
 * Source: free-exercise-db by yuhonas (https://github.com/yuhonas/free-exercise-db),
 * released under the Unlicense (public domain). Exercises with equipment "kettlebells",
 * names tidied, plus a few staples written for Kettlebelt (ids starting with "kb-").
 * Photos load from the GitHub repo for now; bundle or self-host them before release.
 */

export type Pattern = 'hinge' | 'squat' | 'push' | 'pull' | 'getup' | 'carry' | 'core';
export type ExerciseLevel = 'beginner' | 'intermediate' | 'advanced';

export type Exercise = {
  id: string;
  name: string;
  /** Original name in free-exercise-db (empty for our own entries). */
  sourceName: string;
  pattern: Pattern;
  level: ExerciseLevel;
  mechanic: string;
  primary: string[];
  secondary: string[];
  instructions: string[];
  /** Start and finish photos (0–2). */
  images: string[];
};

export const PATTERNS: { id: Pattern; label: string }[] = [
  { id: 'hinge', label: 'Swings & hinges' },
  { id: 'squat', label: 'Squats & lunges' },
  { id: 'push', label: 'Presses' },
  { id: 'pull', label: 'Rows' },
  { id: 'getup', label: 'Get-ups' },
  { id: 'carry', label: 'Carries' },
  { id: 'core', label: 'Core & mobility' },
];

'''


def main():
    data = json.load(urllib.request.urlopen(SRC))
    out = []
    for x in data:
        if x.get('equipment') != 'kettlebells':
            continue
        out.append({
            'id': x['id'], 'name': tidy(x['name']), 'sourceName': x['name'], 'pattern': pattern(x['name']),
            'level': {'expert': 'advanced'}.get(x['level'], x['level']),
            'mechanic': x.get('mechanic') or 'compound',
            'primary': x['primaryMuscles'], 'secondary': x['secondaryMuscles'],
            'instructions': x['instructions'], 'images': [IMG + i for i in x['images']],
        })
    for e in EXTRA:
        out.append({'sourceName': '', 'mechanic': 'compound', 'images': [], **e})
    out.sort(key=lambda e: e['name'].lower())
    body = 'export const exercises: Exercise[] = ' + json.dumps(out, indent=2, ensure_ascii=False) + ';\n\n'
    body += 'export const findExercise = (id: string) => exercises.find((e) => e.id === id);\n'
    with open(OUT, 'w') as f:
        f.write(HEADER + body)
    print(f'wrote {len(out)} exercises to {os.path.normpath(OUT)}')


if __name__ == '__main__':
    main()
