/**
 * Kettlebell exercise library. GENERATED by scripts/build-exercises.py; edit the script, not this file.
 *
 * Source: free-exercise-db by yuhonas (https://github.com/yuhonas/free-exercise-db),
 * released under the Unlicense (public domain). Exercises with equipment "kettlebells",
 * names tidied, plus a few staples written for Kettlebelt (ids starting with "kb-").
 * Photos load from the GitHub repo for now; bundle or self-host them before release.
 */

export type Pattern = 'hinge' | 'squat' | 'push' | 'pull' | 'getup' | 'carry' | 'core';
export type ExerciseLevel = 'beginner' | 'intermediate' | 'advanced';

export type Exercise = {
  id: string;
  name: string;
  /** Original name in free-exercise-db (empty for our own entries). */
  sourceName: string;
  pattern: Pattern;
  level: ExerciseLevel;
  mechanic: string;
  primary: string[];
  secondary: string[];
  instructions: string[];
  /** Start and finish photos (0–2). */
  images: string[];
};

export const PATTERNS: { id: Pattern; label: string }[] = [
  { id: 'hinge', label: 'Swings & hinges' },
  { id: 'squat', label: 'Squats & lunges' },
  { id: 'push', label: 'Presses' },
  { id: 'pull', label: 'Rows' },
  { id: 'getup', label: 'Get-ups' },
  { id: 'carry', label: 'Carries' },
  { id: 'core', label: 'Core & mobility' },
];

export const exercises: Exercise[] = [
  {
    "id": "Advanced_Kettlebell_Windmill",
    "name": "Advanced windmill",
    "sourceName": "Advanced Kettlebell Windmill",
    "pattern": "core",
    "level": "intermediate",
    "mechanic": "isolation",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Clean and press a kettlebell overhead with one arm.",
      "Keeping the kettlebell locked out at all times, push your butt out in the direction of the locked out kettlebell. Keep the non-working arm behind your back and turn your feet out at a forty-five degree angle from the arm with the kettlebell.",
      "Lower yourself as far as possible.",
      "Pause for a second and reverse the motion back to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Advanced_Kettlebell_Windmill/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Advanced_Kettlebell_Windmill/1.jpg"
    ]
  },
  {
    "id": "Alternating_Floor_Press",
    "name": "Alternating floor press",
    "sourceName": "Alternating Floor Press",
    "pattern": "push",
    "level": "beginner",
    "mechanic": "compound",
    "primary": [
      "chest"
    ],
    "secondary": [
      "abdominals",
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Lie on the floor with two kettlebells next to your shoulders.",
      "Position one in place on your chest and then the other, gripping the kettlebells on the handle with the palms facing forward.",
      "Extend both arms, so that the kettlebells are being held above your chest. Lower one kettlebell, bringing it to your chest and turn the wrist in the direction of the locked out kettlebell.",
      "Raise the kettlebell and repeat on the opposite side."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Floor_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Floor_Press/1.jpg"
    ]
  },
  {
    "id": "Alternating_Hang_Clean",
    "name": "Alternating hang clean",
    "sourceName": "Alternating Hang Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "biceps",
      "calves",
      "forearms",
      "glutes",
      "lower back",
      "traps"
    ],
    "instructions": [
      "Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.",
      "Clean one kettlebell to your shoulder and hold on to the other kettlebell in a hanging position. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulders. Rotate your wrist as you do so.",
      "Lower the cleaned kettlebell to a hanging position and clean the alternate kettlebell. Repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Hang_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Hang_Clean/1.jpg"
    ]
  },
  {
    "id": "Alternating_Kettlebell_Press",
    "name": "Alternating press",
    "sourceName": "Alternating Kettlebell Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you pull the kettlebells towards your shoulders. Rotate your wrists as you do so.",
      "Press one directly overhead by extending through the elbow, turning it so the palm faces forward while holding the other kettlebell stationary .",
      "Lower the pressed kettlebell to the starting position and immediately press with your other arm."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Kettlebell_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Kettlebell_Press/1.jpg"
    ]
  },
  {
    "id": "Alternating_Renegade_Row",
    "name": "Alternating renegade row",
    "sourceName": "Alternating Renegade Row",
    "pattern": "pull",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "middle back"
    ],
    "secondary": [
      "abdominals",
      "biceps",
      "chest",
      "lats",
      "triceps"
    ],
    "instructions": [
      "Place two kettlebells on the floor about shoulder width apart. Position yourself on your toes and your hands as though you were doing a pushup, with the body straight and extended. Use the handles of the kettlebells to support your upper body. You may need to position your feet wide for support.",
      "Push one kettlebell into the floor and row the other kettlebell, retracting the shoulder blade of the working side as you flex the elbow, pulling it to your side.",
      "Then lower the kettlebell to the floor and begin the kettlebell in the opposite hand. Repeat for several reps."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Renegade_Row/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Renegade_Row/1.jpg"
    ]
  },
  {
    "id": "Alternating_Kettlebell_Row",
    "name": "Alternating row",
    "sourceName": "Alternating Kettlebell Row",
    "pattern": "pull",
    "level": "intermediate",
    "mechanic": "isolation",
    "primary": [
      "middle back"
    ],
    "secondary": [
      "biceps",
      "lats"
    ],
    "instructions": [
      "Place two kettlebells in front of your feet. Bend your knees slightly and push your butt out as much as possible. As you bend over to get into the starting position grab both kettlebells by the handles.",
      "Pull one kettlebell off of the floor while holding on to the other kettlebell. Retract the shoulder blade of the working side, as you flex the elbow, drawing the kettlebell towards your stomach or rib cage.",
      "Lower the kettlebell in the working arm and repeat with your other arm."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Kettlebell_Row/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Kettlebell_Row/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Arnold_Press",
    "name": "Arnold press",
    "sourceName": "Kettlebell Arnold Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean a kettlebell to your shoulder. Clean the kettlebell to your shoulder by extending through the legs and hips as you raise the kettlebell towards your shoulder. The palm should be facing inward.",
      "Looking straight ahead, press the kettlebell out and overhead, rotating your wrist so that your palm faces forward at the top of the motion.",
      "Return the kettlebell to the starting position, with the palm facing in."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Arnold_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Arnold_Press/1.jpg"
    ]
  },
  {
    "id": "Bent_Press",
    "name": "Bent press",
    "sourceName": "Bent Press",
    "pattern": "push",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "lower back",
      "quadriceps",
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Clean a kettlebell to your shoulder. Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so. This will be your starting position.",
      "Begin my leaning to the side opposite the kettlebell, continuing until you are able to touch the ground with your free hand, keeping your eyes on the kettlebell. As you do so, press the weight vertically be extending through the elbow, keeping your arm perpendicular to the ground.",
      "Return to an upright position, with the kettlebell above your head. Return the kettlebell to the shoulder and repeat for the desired number of repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Press/1.jpg"
    ]
  },
  {
    "id": "Bottoms-Up_Clean_From_The_Hang_Position",
    "name": "Bottoms-up clean from the hang position",
    "sourceName": "Bottoms-Up Clean From The Hang Position",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "forearms"
    ],
    "secondary": [
      "biceps",
      "shoulders"
    ],
    "instructions": [
      "Initiate the exercise by standing upright with a kettlebell in one hand.",
      "Swing the kettlebell back forcefully and then reverse the motion forcefully. Crush the kettlebell handle as hard as possible and raise the kettlebell to your shoulder."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bottoms-Up_Clean_From_The_Hang_Position/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bottoms-Up_Clean_From_The_Hang_Position/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Dead_Clean",
    "name": "Dead clean",
    "sourceName": "Kettlebell Dead Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "calves",
      "glutes",
      "lower back",
      "quadriceps",
      "traps"
    ],
    "instructions": [
      "Place kettlebell between your feet. To get in the starting position, push your butt back and look straight ahead.",
      "Clean the kettlebell to your shoulder. Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.",
      "Lower the kettlebell, keeping the hamstrings loaded by keeping your back straight and your butt out."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Dead_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Dead_Clean/1.jpg"
    ]
  },
  {
    "sourceName": "",
    "mechanic": "compound",
    "images": [],
    "id": "kb-deadlift",
    "name": "Deadlift",
    "pattern": "hinge",
    "level": "beginner",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "glutes",
      "lower back",
      "quadriceps"
    ],
    "instructions": [
      "Stand with the bell between your feet, handle in line with your ankles.",
      "Push the hips back, keep your back flat and grip the handle with both hands.",
      "Brace and stand up tall by pushing the floor away.",
      "Lower the bell under control by hinging back the same way."
    ]
  },
  {
    "id": "Double_Kettlebell_Alternating_Hang_Clean",
    "name": "Double alternating hang clean",
    "sourceName": "Double Kettlebell Alternating Hang Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "biceps",
      "calves",
      "forearms",
      "glutes",
      "lower back",
      "quadriceps",
      "traps"
    ],
    "instructions": [
      "Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.",
      "Clean one kettlebell to your shoulder and hold on to the other kettlebell.",
      "With a fluid motion, lower the top kettlebell while driving the bottom kettlebell up."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Alternating_Hang_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Alternating_Hang_Clean/1.jpg"
    ]
  },
  {
    "id": "Double_Kettlebell_Jerk",
    "name": "Double jerk",
    "sourceName": "Double Kettlebell Jerk",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Hold a kettlebell by the handle in each hand.",
      "Clean the kettlebells to your shoulders by extending through the legs and hips as you pull the kettlebells towards your shoulders. Rotate your wrists as you do so, so that the palms face forward. This will be your starting position.",
      "Dip your body by bending the knees, keeping your torso upright.",
      "Immediately reverse direction, driving through the heels, in essence jumping to create momentum.",
      "As you do so, press the kettlebells overhead to lockout by extending the arms, using your body's momentum to move the weights.",
      "Return your feet to the ground in a split fashion, with one foot forward and one foot back.",
      "Keeping the weights overhead, return to a standing position, bringing your feet together. Lower the weights to perform the next repetition."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Jerk/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Jerk/1.jpg"
    ]
  },
  {
    "id": "Double_Kettlebell_Push_Press",
    "name": "Double push press",
    "sourceName": "Double Kettlebell Push Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders.",
      "Squat down a few inches and reverse the motion rapidly. Use the momentum from the legs to drive the kettlebells overhead.",
      "Once the kettlebells are locked out, lower the kettlebells to your shoulders and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Push_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Push_Press/1.jpg"
    ]
  },
  {
    "id": "Double_Kettlebell_Snatch",
    "name": "Double snatch",
    "sourceName": "Double Kettlebell Snatch",
    "pattern": "hinge",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "quadriceps"
    ],
    "instructions": [
      "Place two kettlebells behind your feet. Bend your knees and sit back to pick up the kettlebells.",
      "Swing the kettlebells between your legs forcefully and reverse the direction.",
      "Drive through with your hips and lock the ketttlebells overhead in one uninterrupted motion."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Snatch/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Snatch/1.jpg"
    ]
  },
  {
    "id": "Double_Kettlebell_Windmill",
    "name": "Double windmill",
    "sourceName": "Double Kettlebell Windmill",
    "pattern": "core",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Place a kettlebell in front of your front foot and clean and press a kettlebell overhead with your opposite arm. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulders. Rotate your wrist as you do so, so that the palm faces forward.",
      "Keeping the kettlebell locked out at all times, push your butt out in the direction of the locked out kettlebell. Turn your feet out at a forty-five degree angle from the arm with the locked out kettlebell.",
      "Bending at the hip to one side, sticking your butt out, slowly lean until you can retrieve the kettlebell from the floor. Keep your eyes on the kettlebell that you hold over your head at all times.",
      "Pause for a second after retrieving the kettlebell from the ground and reverse the motion back to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Windmill/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Windmill/1.jpg"
    ]
  },
  {
    "id": "Extended_Range_One-Arm_Kettlebell_Floor_Press",
    "name": "Extended range one-arm floor press",
    "sourceName": "Extended Range One-Arm Kettlebell Floor Press",
    "pattern": "push",
    "level": "beginner",
    "mechanic": "compound",
    "primary": [
      "chest"
    ],
    "secondary": [
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Lie on the floor and position a kettlebell for one arm to press. The kettlebell should be held by the handle. The leg on the same side that you are pressing should be bent, with the knee crossing over the midline of the body.",
      "Press the kettlebell by extending the elbow and adducting the arm, pressing it above your body. Return to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Extended_Range_One-Arm_Kettlebell_Floor_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Extended_Range_One-Arm_Kettlebell_Floor_Press/1.jpg"
    ]
  },
  {
    "sourceName": "",
    "mechanic": "compound",
    "images": [],
    "id": "kb-farmer-carry",
    "name": "Farmer carry",
    "pattern": "carry",
    "level": "beginner",
    "primary": [
      "forearms"
    ],
    "secondary": [
      "traps",
      "abdominals",
      "shoulders"
    ],
    "instructions": [
      "Deadlift a bell in each hand.",
      "Stand tall with shoulders down and back.",
      "Walk with short, steady steps for the set distance or time.",
      "Set the bells down by hinging, not rounding your back."
    ]
  },
  {
    "id": "Kettlebell_Figure_8",
    "name": "Figure 8",
    "sourceName": "Kettlebell Figure 8",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Place one kettlebell between your legs and take a wider than shoulder width stance. Bend over by pushing your butt out and keeping your back flat.",
      "Pick up a kettlebell and pass it to your other hand between your legs. The receiving hand should reach from behind the legs. Go back and forth for several repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Figure_8/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Figure_8/1.jpg"
    ]
  },
  {
    "id": "Front_Squats_With_Two_Kettlebells",
    "name": "Front squat, two bells",
    "sourceName": "Front Squats With Two Kettlebells",
    "pattern": "squat",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "glutes"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you pull the kettlebells towards your shoulders. Rotate your wrists as you do so.",
      "Looking straight ahead at all times, squat as low as you can and pause at the bottom. As you squat down, push your knees out. You should squat between your legs, keeping an upright torso, with your head and chest up.",
      "Rise back up by driving through your heels and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Squats_With_Two_Kettlebells/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Squats_With_Two_Kettlebells/1.jpg"
    ]
  },
  {
    "id": "Goblet_Squat",
    "name": "Goblet squat",
    "sourceName": "Goblet Squat",
    "pattern": "squat",
    "level": "beginner",
    "mechanic": "compound",
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "glutes",
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Stand holding a light kettlebell by the horns close to your chest. This will be your starting position.",
      "Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight.",
      "At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Halo",
    "name": "Halo",
    "sourceName": "Kettlebell Halo",
    "pattern": "core",
    "level": "beginner",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "traps",
      "middle back",
      "abdominals",
      "triceps"
    ],
    "instructions": [
      "Stand tall with your feet hip-width apart. Hold a kettlebell upside down by the horns, with the bell above your hands and close to your chest. Brace your abdominals and squeeze your glutes so your ribcage stays down. This is your starting position.",
      "Keeping your elbows close to your head, move the kettlebell up past one ear and around behind your head.",
      "Continue the circle past the opposite ear and back down to the starting position in front of your chest, letting the bell pass close to your body throughout.",
      "Complete the prescribed number of circles in one direction, then repeat the same number in the opposite direction.",
      "Move slowly and keep your head, hips and lower back still. If your lower back arches or the bell drifts far from your head, use a lighter weight."
    ],
    "images": []
  },
  {
    "id": "Kettlebell_Halo_With_Overhead_Extension",
    "name": "Halo with overhead extension",
    "sourceName": "Kettlebell Halo with Overhead Extension",
    "pattern": "core",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders",
      "triceps"
    ],
    "secondary": [
      "traps",
      "middle back",
      "abdominals"
    ],
    "instructions": [
      "Stand tall with your feet hip-width apart. Hold a kettlebell upside down by the horns, with the bell above your hands and close to your chest. Brace your abdominals and squeeze your glutes so your ribcage stays down. This is your starting position.",
      "Keeping your elbows close to your head, move the kettlebell up past one ear and around until it sits behind your head. Pause here.",
      "From this position, extend your elbows to press the kettlebell up and overhead until your arms are straight, keeping your upper arms alongside your head.",
      "Bend your elbows to lower the kettlebell back to the pause position behind your head, under control.",
      "Continue the circle past the opposite ear and back down to the starting position in front of your chest to complete one repetition.",
      "Alternate the direction of the circle on each repetition. Keep your head, hips and lower back still throughout; if your lower back arches or you cannot reach the overhead position without leaning back, use a lighter weight or perform the halo and the extension as separate exercises."
    ],
    "images": []
  },
  {
    "id": "Kettlebell_Hang_Clean",
    "name": "Hang clean",
    "sourceName": "Kettlebell Hang Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "calves",
      "glutes",
      "lower back",
      "shoulders",
      "traps"
    ],
    "instructions": [
      "Place kettlebell between your feet. To get in the starting position, push your butt back and look straight ahead.",
      "Clean kettlebell to your shoulder. Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.",
      "Lower kettlebell to a hanging position between your legs while keeping the hamstrings loaded. Keep your head up at all times."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Hang_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Hang_Clean/1.jpg"
    ]
  },
  {
    "id": "Leg-Over_Floor_Press",
    "name": "Leg-over floor press",
    "sourceName": "Leg-Over Floor Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "chest"
    ],
    "secondary": [
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Lie on the floor with one kettlebell in place on your chest, holding it by the handle. Extend leg on working side over leg on non-working side.Your free arm can be extended out to your side for support.",
      "Press the kettlebll into a locked out position.",
      "Lower the weight until the elbow touches the ground, keeping the kettlebell above the elbow. Repeat for the desired number of repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg-Over_Floor_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg-Over_Floor_Press/1.jpg"
    ]
  },
  {
    "id": "Lunge_Pass_Through",
    "name": "Lunge pass through",
    "sourceName": "Lunge Pass Through",
    "pattern": "squat",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "calves",
      "glutes",
      "quadriceps"
    ],
    "instructions": [
      "Stand with your torso upright holding a kettlebell in your right hand. This will be your starting position.",
      "Step forward with your left foot and lower your upper body down by flexing the hip and the knee, keeping the torso upright. Lower your back knee until it nearly touches the ground.",
      "As you lunge, pass the kettlebell under your front leg to your opposite hand.",
      "Pressing through the heel of your foot, return to the starting position.",
      "Repeat the movement for the recommended amount of repetitions, alternating legs."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lunge_Pass_Through/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lunge_Pass_Through/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Clean",
    "name": "One-arm clean",
    "sourceName": "One-Arm Kettlebell Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "glutes",
      "lower back",
      "shoulders",
      "traps"
    ],
    "instructions": [
      "Place a kettlebell between your feet. As you bend down to grab the kettlebell, push your butt back and keep your eyes looking forward.",
      "Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.",
      "Return the weight to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Clean/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Clean_and_Jerk",
    "name": "One-arm clean and jerk",
    "sourceName": "One-Arm Kettlebell Clean and Jerk",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [],
    "instructions": [
      "Hold a kettlebell by the handle.",
      "Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward.",
      "Dip your body by bending the knees, keeping your torso upright.",
      "Immediately reverse direction, driving through the heels, in essence jumping to create momentum. As you do so, press the kettlebell overhead to lockout by extending the arms, using your body's momentum to move the weight.",
      "Receive the weight overhead by returning to a squat position underneath the weight.",
      "Keeping the weight overhead, return to a standing position. Lower the weight to the floor to perform the next repetition."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Clean_and_Jerk/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Clean_and_Jerk/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Floor_Press",
    "name": "One-arm floor press",
    "sourceName": "One-Arm Kettlebell Floor Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "chest"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Lie on the floor holding a kettlebell with one hand, with your upper arm supported by the floor. The palm should be facing in.",
      "Press the kettlebell straight up toward the ceiling, rotating your wrist.",
      "Lower the kettlebell back to the starting position and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Floor_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Floor_Press/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Jerk",
    "name": "One-arm jerk",
    "sourceName": "One-Arm Kettlebell Jerk",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Hold a kettlebell by the handle. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward. This will be your starting position.",
      "Dip your body by bending the knees, keeping your torso upright.",
      "Immediately reverse direction, driving through the heels, in essence jumping to create momentum. As you do so, press the kettlebell overhead to lockout by extending the arms, using your body's momentum to move the weight. Receive the weight overhead by returning to a squat position underneath the weight. Keeping the weight overhead, return to a standing position.",
      "Lower the weight to perform the next repetition."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Jerk/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Jerk/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Military_Press_To_The_Side",
    "name": "One-arm military press to the side",
    "sourceName": "One-Arm Kettlebell Military Press To The Side",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean a kettlebell to your shoulder. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces inward. This will be your starting position.",
      "Look at the kettlebell and press it up and out until it is locked out overhead.",
      "Lower the kettlebell back to your shoulder under control and repeat. Make sure to contract your lat, butt, and stomach forcefully for added stability and strength."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Military_Press_To_The_Side/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Military_Press_To_The_Side/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Open_Palm_Kettlebell_Clean",
    "name": "One-arm open palm clean",
    "sourceName": "One-Arm Open Palm Kettlebell Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "forearms",
      "glutes",
      "lower back",
      "quadriceps",
      "shoulders"
    ],
    "instructions": [
      "Place one kettlebell between your feet.",
      "Grab the handle with one hand and raise the kettlebell rapidly, let it flip so that the ball of the kettlebell lands in the palm of your hand.",
      "Throw the kettlebell out in front of you and catch the handle with one hand.",
      "Take the kettlebell to the floor and repeat. Make sure to work both arms."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Open_Palm_Kettlebell_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Open_Palm_Kettlebell_Clean/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Overhead_Kettlebell_Squats",
    "name": "One-arm overhead squat",
    "sourceName": "One-Arm Overhead Kettlebell Squats",
    "pattern": "squat",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "glutes",
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Clean and press a kettlebell with one arm. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so. Press the weight overhead by extending through the elbow.This will be your starting position.",
      "Looking straight ahead and keeping a kettlebell locked out above you, flex the knees and hips and lower your torso between your legs, keeping your head and chest up.",
      "Pause at the bottom position for a second before rising back to the top, driving through the heels of your feet."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Overhead_Kettlebell_Squats/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Overhead_Kettlebell_Squats/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Para_Press",
    "name": "One-arm para press",
    "sourceName": "One-Arm Kettlebell Para Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean a kettlebell to your shoulder. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward. This will be your starting position.",
      "Hold the kettlebell with the elbow out to the side, and press it up and out until it is locked out overhead.",
      "Lower the kettlebell back to your shoulder under control and repeat. Make sure to contract your lat, butt, and stomach forcefully for added stability and strength."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Para_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Para_Press/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Push_Press",
    "name": "One-arm push press",
    "sourceName": "One-Arm Kettlebell Push Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Hold a kettlebell by the handle. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward. This will be your starting position.",
      "Dip your body by bending the knees, keeping your torso upright.",
      "Immediately reverse direction, driving through the heels, in essence jumping to create momentum. As you do so, press the kettlebell overhead to lockout by extending the arms, using your body's momentum to move the weight. Lower the weight to perform the next repetition."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Push_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Push_Press/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Row",
    "name": "One-arm row",
    "sourceName": "One-Arm Kettlebell Row",
    "pattern": "pull",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "middle back"
    ],
    "secondary": [
      "biceps",
      "lats"
    ],
    "instructions": [
      "Place a kettlebell in front of your feet. Bend your knees slightly and then push your butt out as much as possible as you bend over to get in the starting position. Grab the kettlebell and pull it to your stomach, retracting your shoulder blade and flexing the elbow. Keep your back straight. Lower and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Row/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Row/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Snatch",
    "name": "One-arm snatch",
    "sourceName": "One-Arm Kettlebell Snatch",
    "pattern": "hinge",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "glutes",
      "hamstrings",
      "lower back",
      "traps",
      "triceps"
    ],
    "instructions": [
      "Place a kettlebell between your feet. Bend your knees and push your butt back to get in the proper starting position.",
      "Look straight ahead and swing the kettlebell back between your legs.",
      "Immediately reverse the direction and drive through with your hips and knees, accelerating the kettlebell upward. As the kettlebell rises to your shoulder rotate your hand and punch straight up, using momentum to receive the weight locked out overhead."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Snatch/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Snatch/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Split_Jerk",
    "name": "One-arm split jerk",
    "sourceName": "One-Arm Kettlebell Split Jerk",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Hold a kettlebell by the handle. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward. This will be your starting position.",
      "Dip your body by bending the knees, keeping your torso upright.",
      "Immediately reverse direction, driving through the heels, in essence jumping to create momentum. As you do so, press the kettlebell overhead to lockout by extending the arms, using your body's momentum to move the weight.",
      "Receive the weight overhead by returning to a squat position underneath the weight, positioning one leg in front of you and one leg behind you.",
      "Keeping the weight overhead, return to a standing position and bring your feet together. Lower the weight to perform the next repetition."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Split_Jerk/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Split_Jerk/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Split_Snatch",
    "name": "One-arm split snatch",
    "sourceName": "One-Arm Kettlebell Split Snatch",
    "pattern": "hinge",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "hamstrings",
      "quadriceps"
    ],
    "instructions": [
      "Hold a kettlebell in one hand by the handle.",
      "Squat towards the floor, and then reverse the motion, extending the hips, knees, and finally the ankles, to raise the kettlebell overhead.",
      "After fully extending the body, descend into a lunge position to receive the weights overhead, one leg forward and one leg back. Ensure you drive through with your hips and lock the ketttlebells overhead in one uninterrupted motion.",
      "Return to a standing position, holding the weight overhead, and bring the feet together. Lower the weight to return to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Split_Snatch/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Split_Snatch/1.jpg"
    ]
  },
  {
    "id": "One-Arm_Kettlebell_Swings",
    "name": "One-arm swing",
    "sourceName": "One-Arm Kettlebell Swings",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "calves",
      "glutes",
      "lower back",
      "shoulders"
    ],
    "instructions": [],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_One-Legged_Deadlift",
    "name": "One-legged deadlift",
    "sourceName": "Kettlebell One-Legged Deadlift",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "glutes",
      "lower back"
    ],
    "instructions": [
      "Hold a kettlebell by the handle in one hand. Stand on one leg, on the same side that you hold the kettlebell.",
      "Keeping that knee slightly bent, perform a stiff legged deadlift by bending at the hip, extending your free leg behind you for balance.",
      "Continue lowering the kettlebell until you are parallel to the ground, and then return to the upright position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_One-Legged_Deadlift/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_One-Legged_Deadlift/1.jpg"
    ]
  },
  {
    "id": "Open_Palm_Kettlebell_Clean",
    "name": "Open palm clean",
    "sourceName": "Open Palm Kettlebell Clean",
    "pattern": "hinge",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "glutes",
      "lower back",
      "quadriceps",
      "shoulders"
    ],
    "instructions": [
      "Place one kettlebell between your feet. Clean the kettlebell by extending through the legs and hips as you raise the kettlebell towards your shoulders.",
      "Release the kettlebell as it comes up, and let it flip so that the ball of the kettlebell lands in the palms of your hands.",
      "Release the kettlebell out in front of you and catch the handle with both hands. Lower the kettlebell to the starting position and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Open_Palm_Kettlebell_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Open_Palm_Kettlebell_Clean/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Overhead_Triceps_Extension",
    "name": "Overhead triceps extension",
    "sourceName": "Kettlebell Overhead Triceps Extension",
    "pattern": "push",
    "level": "beginner",
    "mechanic": "isolation",
    "primary": [
      "triceps"
    ],
    "secondary": [
      "shoulders",
      "abdominals"
    ],
    "instructions": [
      "Stand with your feet hip-width apart, holding a kettlebell by the horns with both hands. Press it overhead until your arms are extended, with the bell hanging behind your hands.",
      "Brace your abdominals and keep your upper arms vertical and close to your head. This is your starting position.",
      "Bend at the elbows to lower the kettlebell behind your head, going as far as your shoulder mobility allows without your elbows flaring outward.",
      "Extend your elbows to press the kettlebell back to the starting position, keeping your upper arms still throughout.",
      "Keep your ribcage down and avoid arching your lower back as you extend."
    ],
    "images": []
  },
  {
    "id": "Kettlebell_Pass_Between_The_Legs",
    "name": "Pass between the legs",
    "sourceName": "Kettlebell Pass Between The Legs",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Place one kettlebell between your legs and take a comfortable stance. Bend over by pushing your butt out and keeping your back flat.",
      "Pick up a kettlebell and pass it to your other hand between your legs, in the fashion of a \"W\". Go back and forth for several repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pass_Between_The_Legs/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pass_Between_The_Legs/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Pirate_Ships",
    "name": "Pirate ships",
    "sourceName": "Kettlebell Pirate Ships",
    "pattern": "core",
    "level": "beginner",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "abdominals"
    ],
    "instructions": [
      "With a wide stance, hold a kettlebell with both hands. Allow it to hang at waist level with your arms extended. This will be your starting position.",
      "Initiate the movement by turning to one side, swinging the kettlebell to head height. Briefly pause at the top of the motion.",
      "Allow the bell to drop as you rotate to the opposite side, again raising the kettlebell to head height.",
      "Repeat for the desired amount of repetitions."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pirate_Ships/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pirate_Ships/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Pistol_Squat",
    "name": "Pistol squat",
    "sourceName": "Kettlebell Pistol Squat",
    "pattern": "squat",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "glutes",
      "hamstrings",
      "shoulders"
    ],
    "instructions": [
      "Pick up a kettlebell with two hands and hold it by the horns. Hold one leg off of the floor and squat down on the other.",
      "Squat down by flexing the knee and sitting back with the hips, holding the kettlebell up in front of you.",
      "Hold the bottom position for a second and then reverse the motion, driving through the heel and keeping your head and chest up.",
      "Lower yourself again and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pistol_Squat/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pistol_Squat/1.jpg"
    ]
  },
  {
    "id": "Plyo_Kettlebell_Pushups",
    "name": "Plyo push-ups",
    "sourceName": "Plyo Kettlebell Pushups",
    "pattern": "push",
    "level": "advanced",
    "mechanic": "compound",
    "primary": [
      "chest"
    ],
    "secondary": [
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Place a kettlebell on the floor. Place yourself in a pushup position, on your toes with one hand on the ground and one hand holding the kettlebell, with your elbows extended. This will be your starting position.",
      "Begin by lowering yourself as low as you can, keeping your back straight.",
      "Quickly and forcefully reverse direction, pushing yourself up to the other side of the kettlebell, switching hands as you do so. Continue the movement by descending and repeating the movement back and forth."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plyo_Kettlebell_Pushups/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plyo_Kettlebell_Pushups/1.jpg"
    ]
  },
  {
    "sourceName": "",
    "mechanic": "compound",
    "images": [],
    "id": "kb-rack-carry",
    "name": "Rack carry",
    "pattern": "carry",
    "level": "intermediate",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "shoulders",
      "forearms"
    ],
    "instructions": [
      "Clean a bell to the rack position: wrist straight, bell on the forearm, elbow tucked.",
      "Brace your midsection and stand tall.",
      "Walk with steady steps for the set distance.",
      "Switch sides and repeat."
    ]
  },
  {
    "id": "Kettlebell_Seated_Press",
    "name": "Seated press",
    "sourceName": "Kettlebell Seated Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Sit on the floor and spread your legs out comfortably.",
      "Clean one kettlebell to your shoulder.",
      "Press the kettlebell up and out until it is locked out overhead. Return to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Seated_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Seated_Press/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Seesaw_Press",
    "name": "Seesaw press",
    "sourceName": "Kettlebell Seesaw Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells two your shoulders.",
      "Press one kettlebell.",
      "Lower the kettlebell and immediately press the other kettlebell. Make sure to do the same amount of reps on both sides."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Seesaw_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Seesaw_Press/1.jpg"
    ]
  },
  {
    "sourceName": "",
    "mechanic": "compound",
    "images": [],
    "id": "kb-suitcase-carry",
    "name": "Suitcase carry",
    "pattern": "carry",
    "level": "beginner",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "forearms",
      "traps"
    ],
    "instructions": [
      "Deadlift one bell to your side.",
      "Stand tall without leaning toward or away from the bell.",
      "Walk with steady steps, keeping hips and shoulders level.",
      "Switch hands and repeat."
    ]
  },
  {
    "id": "Kettlebell_Sumo_High_Pull",
    "name": "Sumo high pull",
    "sourceName": "Kettlebell Sumo High Pull",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "traps"
    ],
    "secondary": [
      "adductors",
      "glutes",
      "hamstrings",
      "quadriceps",
      "shoulders"
    ],
    "instructions": [
      "Place a kettlebell on the ground between your feet. Position your feet in a wide stance, and grasp the kettlebell with two hands. Set your hips back as far as possible, with your knees bent. Keep your chest and head up. This will be your starting position.",
      "Begin by extending the hips and knees, simultaneously pulling the kettlebell to your shoulders, raising your elbows as you do so. Reverse the motion to return to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Sumo_High_Pull/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Sumo_High_Pull/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Thruster",
    "name": "Thruster",
    "sourceName": "Kettlebell Thruster",
    "pattern": "squat",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you pull the kettlebells towards your shoulders. Rotate your wrists as you do so. This will be your starting position.",
      "Begin to squat by flexing your hips and knees, lowering your hips between your legs. Maintain an upright, straight back as you descend as low as you can.",
      "At the bottom, reverse direction and squat by extending your knees and hips, driving through your heels. As you do so, press both kettlebells overhead by extending your arms straight up, using the momentum from the squat to help drive the weights upward.",
      "As you begin the next repetition, return the weights to the shoulders."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Thruster/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Thruster/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Turkish_Get-Up_Lunge_style",
    "name": "Turkish get-up (lunge style)",
    "sourceName": "Kettlebell Turkish Get-Up (Lunge style)",
    "pattern": "getup",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "abdominals",
      "hamstrings",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Lie on your back on the floor and press a kettlebell to the top position by extending the elbow. Bend the knee on the same side as the kettlebell.",
      "Keeping the kettlebell locked out at all times, pivot to the opposite side and use your non- working arm to assist you in driving forward to the lunge position. Using your free hand, push yourself to a seated position, then progressing to one knee.",
      "While looking up at the kettlebell, slowly stand up. Reverse the motion back to the starting position and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Lunge_style/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Lunge_style/1.jpg"
    ]
  },
  {
    "id": "Kettlebell_Turkish_Get-Up_Squat_style",
    "name": "Turkish get-up (squat style)",
    "sourceName": "Kettlebell Turkish Get-Up (Squat style)",
    "pattern": "getup",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "abdominals",
      "calves",
      "hamstrings",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Lie on your back on the floor and press a kettlebell to the top position by extending the elbow. Bend the knee on the same side as the kettlebell.",
      "Keeping the kettlebell locked out at all times, pivot to the opposite side and use your non- working arm to assist you in driving forward to the lunge position.",
      "Using your free hand, push yourself to a seated position, then progressing to your feet. While looking up at the kettlebell, slowly stand up. Reverse the motion back to the starting position and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Squat_style/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Squat_style/1.jpg"
    ]
  },
  {
    "id": "Two-Arm_Kettlebell_Clean",
    "name": "Two-hand clean",
    "sourceName": "Two-Arm Kettlebell Clean",
    "pattern": "hinge",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "glutes",
      "hamstrings",
      "lower back",
      "traps"
    ],
    "instructions": [
      "Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.",
      "Clean the kettlebells to your shoulders by extending through the legs and hips as you raise the kettlebells towards your shoulders. Rotate your wrists as you do so.",
      "Lower the kettlebells back to the starting position and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Clean/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Clean/1.jpg"
    ]
  },
  {
    "id": "Two-Arm_Kettlebell_Jerk",
    "name": "Two-hand jerk",
    "sourceName": "Two-Arm Kettlebell Jerk",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "calves",
      "quadriceps",
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you swing the kettlebells towards your shoulders. Rotate your wrists as you do so, so that the palms face forward. Squat down a few inches and reverse the motion rapidly driving both kettlebells overhead. Immediately after the initial push, squat down again and get under the kettlebells. Once the kettlebells are locked out, stand upright to complete the exercise."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Jerk/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Jerk/1.jpg"
    ]
  },
  {
    "id": "Two-Arm_Kettlebell_Military_Press",
    "name": "Two-hand military press",
    "sourceName": "Two-Arm Kettlebell Military Press",
    "pattern": "push",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "shoulders"
    ],
    "secondary": [
      "triceps"
    ],
    "instructions": [
      "Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you swing the kettlebells towards your shoulders. Rotate your wrists as you do so, so that the palms face forward.",
      "Press the kettlebells up and out. As the kettlebells pass your head, lean into the weights so that the kettlebells are racked behind your head. Make sure to contract your lats, butt, and stomach for added stability."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Military_Press/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Military_Press/1.jpg"
    ]
  },
  {
    "id": "Two-Arm_Kettlebell_Row",
    "name": "Two-hand row",
    "sourceName": "Two-Arm Kettlebell Row",
    "pattern": "pull",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "middle back"
    ],
    "secondary": [
      "biceps",
      "lats"
    ],
    "instructions": [
      "Place two kettlebells in front of your feet. Bend your knees slightly and then push your butt out as much as possible as you bend over to get in the starting position.",
      "Grab both kettlebells and pull them to your stomach, retracting your shoulder blades and flexing the elbows. Keep your back straight. Lower and repeat."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Row/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Two-Arm_Kettlebell_Row/1.jpg"
    ]
  },
  {
    "sourceName": "",
    "mechanic": "compound",
    "images": [],
    "id": "kb-two-hand-swing",
    "name": "Two-hand swing",
    "pattern": "hinge",
    "level": "beginner",
    "primary": [
      "hamstrings"
    ],
    "secondary": [
      "glutes",
      "lower back",
      "forearms"
    ],
    "instructions": [
      "Stand with feet a little wider than hips, bell about a foot in front of you.",
      "Hinge at the hips with a flat back and grab the handle with both hands.",
      "Hike the bell back between your legs like a football snap.",
      "Stand up explosively by driving the hips forward; let the bell float to chest height.",
      "Let the bell fall back and hinge again, keeping the arms relaxed."
    ]
  },
  {
    "id": "Kettlebell_Windmill",
    "name": "Windmill",
    "sourceName": "Kettlebell Windmill",
    "pattern": "core",
    "level": "intermediate",
    "mechanic": "compound",
    "primary": [
      "abdominals"
    ],
    "secondary": [
      "glutes",
      "hamstrings",
      "shoulders",
      "triceps"
    ],
    "instructions": [
      "Place a kettlebell in front of your lead foot and clean and press it overhead with your opposite arm. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulders. Rotate your wrist as you do so, so that the palm faces forward. Press it overhead by extending the elbow.",
      "Keeping the kettlebell locked out at all times, push your butt out in the direction of the locked out kettlebell. Turn your feet out at a forty-five degree angle from the arm with the locked out kettlebell. Bending at the hip to one side, sticking your butt out, slowly lean until you can touch the floor with your free hand. Keep your eyes on the kettlebell that you hold over your head at all times.",
      "Pause for a second after reaching the ground and reverse the motion back to the starting position."
    ],
    "images": [
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Windmill/0.jpg",
      "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Windmill/1.jpg"
    ]
  }
];

export const findExercise = (id: string) => exercises.find((e) => e.id === id);
